name: tests

on:
  workflow_dispatch:
  
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
    
      - name: add-secrets
        shell: pwsh
        run: |
          Get-Location

          Get-ChildItem -Recurse

          write-host "Updating .env files"
          $files = get-childitem -Recurse -Filter '.env.*' -File | Select-Object
          foreach ($file in $files) 
            {
                write-host "Updating: " $file.FullName
                Copy-Item  $file.FullName .\

                (Get-Content $file.Name) | % ` { $_-replace '{{PASSWORD}}', $env:PASSWORD } |  Set-Content $file.Name
                (Get-Content $file.Name) | % ` { $_-replace '{{USER}}', $env:USER } |  Set-Content $file.Name
            }
        env:
            PASSWORD: ${{ secrets.PASSWORD }}
            USER: ${{ secrets.USER }}

      - name: read-secrets
        shell: pwsh
        run: |
          write-host "Reading .env files"
          $files = get-childitem -Filter '.env.*' -File | Select-Object
          foreach ($file in $files) 
            {
                write-host "------------"
                write-host "Reading: " $file.FullName

                $text = Get-Content $file.FullName -Raw
                write-host $text

                write-host "------------"
                write-host ""
                write-host ""
            }



